### ISSUE TITLE
Consider consolidating data and equations into one place

### ISSUE THREAD

**Issue by shoyer** [williamgilpin/dysts#3] opened 2021-10-13 17:18 UTC
I'm sure there are reasons why the separate JSON file is convenient, but I found it made it hard to understand exactly what dynamical systems are being solved without installing the Python package.

**Comment by williamgilpin** [comment] 2021-10-14 02:22
Thank you so much for your comment on the code—I am always open to any suggestions on how to make the behind the scenes set up more intuitive!

The basic issue I have is that I want most information to be accessible through an object representing each dynamical system, but I want that object to include (1) a callable RHS for the diffeq and (2) fun facts about the system like its default parameters, estimated Lyapunov exponent, estimated integration timestep, citation reference, whether it’s conservative, etc

For the former, storing the information in a .py file made sense. However, I didn’t like the idea of hard-coding system-specific numbers (especially since I want to retain the ability to write to the file). Conversely, I thought about storing the RHS within the JSON database and loading into Python code when the object is initiated, but that seemed a bit messy. So I ended up splitting it into two files. 

Let me know if you have any suggestions! cheers

**Comment by shoyer** [comment] 2021-10-18 16:10
Some of these values are computed from the attractor (e.g., the Lypaunov spectrum), which I agree would be weird to put into the Python code. So my inclination would be to put everything that describes the system and how to solve it into the class, and to put the variables computed from the system into the JSON data.

**Comment by williamgilpin** [comment] 2023-04-26 18:25
I'm closing this issue for now, because I still haven't found a an alternative design pattern that does everything I need it to.

I played around with putting the function definitions themselves into the JSON file, since that could be useful for symbolic regression algos that want to work with parseable definitions. But importing the strings into python functions caused a lot of bugs, and I couldn't get it to play well with numba. 

Happy to re-open if a better approach jumps out. cheers, william

**Closed by williamgilpin** 2023-04-26 18:25 UTC
